import Foundation

struct SubtitleStream {
    var name: String
    var code: String // subtitle language code
    var autoGenerated: Bool // whether the subtitles are auto-generated
    
    var mimeType: String
    var url: URL
}

extension SubtitleStream: Hashable { }
extension SubtitleStream: Codable { }
extension SubtitleStream: Sendable { }
