import Foundation

public struct SubtitleStream {
    public var name: String
    public var code: String // subtitle language code
    public var autoGenerated: Bool // whether the subtitles are auto-generated
    
    public var mimeType: String
    public var url: URL
}

extension SubtitleStream: Hashable { }
extension SubtitleStream: Codable { }
extension SubtitleStream: Sendable { }
